### PR TITLE
Try to enable ANSI support on Windows

### PR DESCRIPTION
**Pull request by jonpas**
and disable colored output if failed.

### CODE REVIEW

**Comment by jonpas** [comment]
**Top:** before this PR
**Bottom:** with this PR
Colored CMD

**Comment by Krzmbrzl** [comment]
Will this also work on Linux? Or is that implemented already on linux?
(This might be helpful: https://www.linux.org/threads/ansi-codes-and-colorized-terminals.11706/)

**Comment by jonpas** [comment]
`ansi_term::enable_ansi_support` is implemented on Windows only, using Windows API. I haven't heard of a proper Linux terminal that doesn't handle colors, might as well use another terminal in that case. Windows is a special case as always, you have CMD and PowerShell, both of which this function enables colors in.

**Comment by KoffeinFlummi** [comment]
Merged in 40fabd915514ffda372ec012b35ed4190d0e0515

**Pull request closed without merging**
